quarkus.application.name=sdd-petclinic

# Base de datos
quarkus.datasource.db-kind=postgresql

# jOOQ
quarkus.jooq.dialect=POSTGRES

# Flyway ejecuta las migraciones al arrancar
quarkus.flyway.migrate-at-start=true

# Dev Services inicia PostgreSQL automáticamente en modo desarrollo y pruebas
%dev.quarkus.datasource.devservices.image-name=postgres:17-alpine
%test.quarkus.datasource.devservices.image-name=postgres:17-alpine

# Vaadin
%dev.vaadin.launch-browser=true
